name: Require Linked Issue

on: [pull_request]

jobs:
  check-linked-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Check for exactly one linked issue
        uses: actions/github-script@v7
        with:
          script: |
            const linked = await github.rest.issues.listEventsForTimeline({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number
            });

            const linkedIssues = linked.data.filter(e => e.event === 'connected');
            if (linkedIssues.length !== 1) {
              core.setFailed('This PR must be linked to exactly one GitHub Issue.');
            }
